name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: Noble-Build,
             OS_NAME: ubuntu,
             OS_CODE_NAME: noble,
             ROS_DISTRO: jazzy,
             ROS_REPO: main,
             DOCKER_IMAGE: "ros:jazzy"}
          - {CI_NAME: Jammy-Build,
             OS_NAME: ubuntu,
             OS_CODE_NAME: jammy,
             ROS_DISTRO: humble,
             ROS_REPO: main,
             DOCKER_IMAGE: "ros:humble"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
        
